services:
  nginx-proxy:
    build: .
    networks:
      - nginx-network
      - dokploy-network
    ports:
      - 80/tcp
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
networks:
  nginx-network:
    driver: bridge
  dokploy-network:
    external: true
